server:
    port: 8086

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

spring:
     application:
            name: order-config-server
     cloud:
       config:
          server:
            git:
              uri: https://github.com/sagarjate91/order-cloud-config


